 enum BeheshtiUniversityField {
    COMPUTER_SCIENCE,
    LIFE_SCIENCE,
    SPORT_SCIENCE,
    AGRICULTURE_FORESTRY,
    BIOLOGICAL_SCIENCES,
    SOCIAL_SCIENCES,
    ENVIRONMENTAL_STUDIES,
    ENGINEERING_TECHNOLOGY,
    ARTS_HUMANITIES,
    ECONOMICS_BUSINESS,
    NATURAL_SCIENCES_MATH,
    PSYCHOLOGY,
    LAW,
    MEDICINE_HEALTHCARE;


}

